f = open('first_time_wizard.txt', "w+")
f.write('hostname=security_checkup \n')
f.write('mgmt_admin_name=admin \n')
f.write('mgmt_admin_passwd=vpn123 \n')
f.write('mgmt_gui_clients_radio=any \n')
f.write('install_security_managment="true" \n')
f.write('install_security_gw="true" \n')
f.write('install_mgmt_primary="true" \n')
f.write('install_mgmt_secondary="false" \n')
f.write('download_info="true" \n')
f.write('upload_info="true" \n')
f.close()